#!/usr/bin/env python3
"""Sync `.agent-rules/*.md` sources into top-level `CLAUDE.md` and `AGENTS.md`.

Standard-library only — runnable without an activated `.venv/`.

Usage:
    python3 .agent-rules/sync_agent_rules.py            # write outputs
    python3 .agent-rules/sync_agent_rules.py --check    # parse only, no writes
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = ROOT / ".agent-rules"
SOURCES = ("approval.md", "core.md", "style.md")

CLAUDE_HEADER = """# CLAUDE.md

This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository.

<!-- AUTO-GENERATED — edit `.agent-rules/*.md` and run `python3 .agent-rules/sync_agent_rules.py` to regenerate. Do NOT edit this file directly. -->

## Commands

```bash
# 创建虚拟环境（首次）
python3.11 -m venv .venv

# 安装（开发模式，含 Anthropic provider 与开发依赖）
.venv/bin/pip install -e ".[anthropic,dev]"

# 运行 CLI
.venv/bin/paperterm bootstrap <paper_dir>
.venv/bin/paperterm check <paper_dir>

# 输出 standalone bootstrap prompt（必须重定向到 prompts/，不允许手编 — 见 style.md「Prompt 单源规则」）
.venv/bin/paperterm print-prompt > prompts/glossary_bootstrap.md

# 测试
.venv/bin/pytest tests/

# 单测
.venv/bin/pytest tests/test_linter.py::test_skip_math -v

# 同步 agent 规则（编辑 .agent-rules/ 后执行；脚本仅依赖标准库，可用 python3 直接跑）
python3 .agent-rules/sync_agent_rules.py
```

允许的工具白名单见 `.claude/settings.local.json`（本地，不入 git）。

## Codex 代码审查（Claude Code 专用）

当「代码审查（Codex Review Gate）」规则触发时，使用以下 MCP 工具调用 Codex：

```
mcp__codex__codex({
  prompt: "<审查要求与待审查代码的上下文>",
  sandbox: "read-only",
  cwd: "<项目根目录>"
})
```

- 始终使用 `read-only` sandbox，确保审查过程不修改文件
- 如需对审查结果追问，使用 `mcp__codex__codex-reply` 传入 `threadId`
- 审查 prompt 应包含：改动摘要、涉及文件、需关注的审查重点

---
"""

AGENTS_HEADER = """# paperterm — AI Coding Agent 指令

<!-- AUTO-GENERATED — edit `.agent-rules/*.md` and run `python3 .agent-rules/sync_agent_rules.py` to regenerate. Do NOT edit this file directly. -->

> 适用于 Claude Code / Cursor / Codex 等所有 AI coding agent。
> Cursor 用户另见 `.cursor/rules/`（如有）获取完整规则。
> 规则修改请编辑 `.agent-rules/*.md` 后运行 `python3 .agent-rules/sync_agent_rules.py`。

---
"""


def read_sources() -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for name in SOURCES:
        path = RULES_DIR / name
        if not path.is_file():
            raise FileNotFoundError(f"missing source: {path}")
        text = path.read_text(encoding="utf-8").strip("\n")
        if not text.strip():
            raise ValueError(f"empty source (after strip): {path}")
        out.append((name, text))
    return out


def render(header: str, sources: list[tuple[str, str]]) -> str:
    body = "\n\n---\n\n".join(content for _, content in sources)
    return header + body + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    parser.add_argument(
        "--check",
        action="store_true",
        help="parse sources but do not write outputs (used by CI / Stage 1 self-check)",
    )
    args = parser.parse_args(argv)

    try:
        sources = read_sources()
        claude_md = render(CLAUDE_HEADER, sources)
        agents_md = render(AGENTS_HEADER, sources)
    except (FileNotFoundError, ValueError, OSError, UnicodeDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.check:
        print(
            f"check ok: {len(sources)} sources, "
            f"CLAUDE.md={len(claude_md)} chars, "
            f"AGENTS.md={len(agents_md)} chars"
        )
        return 0

    try:
        (ROOT / "CLAUDE.md").write_text(claude_md, encoding="utf-8")
        (ROOT / "AGENTS.md").write_text(agents_md, encoding="utf-8")
    except OSError as exc:
        print(f"error: failed to write output: {exc}", file=sys.stderr)
        return 1

    print(
        f"wrote CLAUDE.md ({len(claude_md)} chars), "
        f"AGENTS.md ({len(agents_md)} chars)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
